name: 'Lint Swift Action'
description: 'Run SwiftLint from your GitHub Actions with ease'
author: 'Cirrus Labs, Inc.'

branding:
  icon: 'activity'
  color: 'green'

inputs:
  version:
    description: 'SwiftLint version to use or "latest" to query the latest available version'
    required: false
    default: 'latest'
  strict:
    description: 'Upgrades warnings to serious violations (errors)'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
