name: 'SwiftLint Action'
description: 'Run SwiftLint from your GitHub Actions with ease'
author: 'Cirrus Labs, Inc.'

branding:
  icon: 'file-text'
  color: 'purple'

inputs:
  version:
    description: 'SwiftLint version to use or "latest" to query the latest available version'
    required: false
    default: 'latest'

runs:
  using: node20
  main: dist/index.js
